package ghidrassistmcp.tools;

import java.util.List;
import java.util.Map;

import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.Program;
import ghidrassistmcp.McpTool;
import io.modelcontextprotocol.spec.McpSchema;

public class GetFunctionStatisticsTool implements McpTool {

    @Override
    public boolean isCacheable() { return true; }

    @Override
    public String getName() { return "get_function_statistics"; }

    @Override
    public String getDescription() { return "Get statistics about functions in the program"; }

    @Override
    public McpSchema.JsonSchema getInputSchema() {
        return new McpSchema.JsonSchema("object", Map.of(), List.of(), null, null, null);
    }

    @Override
    public McpSchema.CallToolResult execute(Map<String, Object> arguments, Program currentProgram) {
        if (currentProgram == null) {
            return McpSchema.CallToolResult.builder().addTextContent("No program currently loaded").build();
        }

        int total = 0, thunks = 0, external = 0, named = 0, autoGenerated = 0;
        long totalParams = 0, totalSize = 0;

        for (Function func : currentProgram.getFunctionManager().getFunctions(true)) {
            total++;
            if (func.isThunk()) thunks++;
            if (func.isExternal()) external++;
            String name = func.getName();
            if (name.startsWith("FUN_") || name.startsWith("sub_") || name.startsWith("thunk_")) {
                autoGenerated++;
            } else {
                named++;
            }
            totalParams += func.getParameterCount();
            totalSize += func.getBody().getNumAddresses();
        }

        StringBuilder sb = new StringBuilder();
        sb.append("Function Statistics:\n\n");
        sb.append("Total functions: ").append(total).append("\n");
        sb.append("Named functions: ").append(named).append("\n");
        sb.append("Auto-generated names: ").append(autoGenerated).append("\n");
        sb.append("Thunk functions: ").append(thunks).append("\n");
        sb.append("External functions: ").append(external).append("\n");
        if (total > 0) {
            sb.append("Average parameters: ").append(String.format("%.1f", (double) totalParams / total)).append("\n");
            sb.append("Total code size: ").append(totalSize).append(" bytes\n");
            sb.append("Average function size: ").append(String.format("%.1f", (double) totalSize / total)).append(" bytes\n");
        }

        return McpSchema.CallToolResult.builder().addTextContent(sb.toString()).build();
    }
}
